export { default as Loader } from './Loader';
export { default as Navbar } from './Navbar';
export { default as NavbarConsumer } from './NavbarConsumer';
export { default as Footer } from './Footer';
export { default as Welcome } from './Welcome';
export { default as Transactions } from './Transactions';
export { default as Services } from './Services';
export { default as Monitor } from './Monitor';
export { default as Home } from './Home';
export { default as Traceability } from './Traceability';
import { BrowserRouter } from 'react-router-dom';
import { database } from '../config/firebase';